### ISSUE TITLE
Is the code open source ?

### ISSUE THREAD

**Issue by nathangemis** [StandardCyborg/StandardCyborgCocoa#24]
Hi, 

We just read this article [https://www.fabbaloo.com/news/3d-capture-app-goes-down](url) that say that the code of the Capture app will be totally open source but at the end of the readme of this repository, it says that the code is closed-source.

There is another repository with the open-source code ?

In case this repository code is open-source and not closed-source, how can we have a token from your API ?
There is another repository with your backend (cloud) code ?

Thank you :)

**Comment by jeffchuber** [comment]
Hi @nathangemis, `StandardCyborgCocoa` is *currently* freeware / closed-source. We are working on isolating the 3D scanning code and providing good documentation so that we can make it fully open source soon!

**Comment by aaptho** [comment]
It’s now 100% open source!
https://github.com/StandardCyborg/StandardCyborgSDK
