### ISSUE TITLE
Changing Unit Measurement for displaying Point Cloud

### ISSUE THREAD

**Issue by martintseng** [StandardCyborg/StandardCyborgCocoa#27]
Currently, when we display the point cloud, it is displayed in meters, but I would like to change it to millimetres. Where in the code, can I change this?

Thanks

**Comment by aaptho** [comment]
This code uses meters throughout the whole codebase, so I’m not sure what you mean.

Are you trying to export a point cloud PLY file with millimeters as the unit?
