### ISSUE TITLE
Unable to access Web site : https://standardcyborg.com

### ISSUE THREAD

**Issue by meichen8050753** [StandardCyborg/StandardCyborgCocoa#29]
I can't open the website, so I can't get the API token (from your platform.standardcyborg.com account)
![image](https://user-images.githubusercontent.com/2345514/189023643-50749c82-afcd-44e4-a3f6-63f2b503bdc1.png)

**Comment by scratchthatitch** [comment]
You shouldn't need the token now as it is open source.
________________________________
From: meichen8050753 ***@***.***>
Sent: 08 September 2022 03:58
To: StandardCyborg/StandardCyborgCocoa ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [StandardCyborg/StandardCyborgCocoa] Unable to access Web site : https://standardcyborg.com (Issue #29)


I can't open the website, so I can't get the API token (from your platform.standardcyborg.com account)
[image]<https://user-images.githubusercontent.com/2345514/189023643-50749c82-afcd-44e4-a3f6-63f2b503bdc1.png>

**Comment by aaptho** [comment]
Ah, thanks for bringing that up—we hadn’t updated the README in this repo yet! Updated now.

And indeed, you no longer need any API keys.
