### ISSUE TITLE
Using LiDAR camera for 3D scanning. Seeing mirrored view. 

### ISSUE THREAD

**Issue by jaswant-iotric** [StandardCyborg/StandardCyborgCocoa#31]
I've successfully updated the code to use the LiDAR camera for 3D scanning. The only issue is the view is mirrored. Cant seem to fix it. Anyone having any idea?

**Comment by aaptho** [comment]
Oh wow, that’s great! Would you mind sharing the code?

To fix the mirrored view, I think if you set `mirrorModeEnabled = true` on the `ScanningViewController` instance, it should flip it. You may also need `flipsInputHorizontally` on `SCReconstructionManager`, depending on how you implemented LiDAR.

**Comment by jaswant-iotric** [comment]
![Screenshot 2023-03-14 at 11 46 35 AM](https://user-images.githubusercontent.com/56866566/224912383-ac70f8f9-1f4e-4fcc-8074-aff7b626ac0b.png)

Line 191 of CameraManager.swift

**Comment by jaswant-iotric** [comment]
Also I've tried your solution but it's not working. Also on pressing the flip camera button. The UI gets distorted. Been trying with no success for hours. 
Make sure to set development target to iOS 15.4 as builtInLiDARCamera isn't available before that.

**Comment by saamerm** [comment]
@jaswant-iotric you might want to switch the value between 0, 1 and -1 on the matrix multiplier and you can get what ever you desire (flip horizontally, vertically, etc)
