### ISSUE TITLE
PLY from or instead of USDZ

### ISSUE THREAD

**Issue by saamerm** [StandardCyborg/StandardCyborgCocoa#33]
The latest version of the library only provides USDZ and not a PLY. Is there a way to extract the ply from it? I’m not able to use any online tools to do this. 
help is appreciated. Right now I just reverted to an older version

**Comment by aaptho** [comment]
Where are you looking? `SCPointCloud` still has the method [-writeToPLYAtPath:](https://github.com/StandardCyborg/StandardCyborgCocoa/blob/4b85c3dd8b0aa24c1af98315baad4825ab0532e8/StandardCyborgFusion/StandardCyborgFusion.xcframework/ios-arm64/StandardCyborgFusion.framework/Headers/SCPointCloud%2BFileIO.h#L22)

When the scan is finished, call `-[SCReconstructionManager buildPointCloud]` to build an `SCPointCloud`.
