### ISSUE TITLE
StandardCyborgExample does not compile: Cannot find type 'ScenePreviewViewController' in scope

### ISSUE THREAD

**Issue by that-corych** [StandardCyborg/StandardCyborgCocoa#36]
![image](https://user-images.githubusercontent.com/56929051/236777155-a3f149da-6581-4f8a-abc9-ef823afb8373.png)

**Comment by aaptho** [comment]
Please provide steps to reproduce this issue and a descriptive issue title.

**Comment by that-corych** [comment]
i clone the repo using instructions and start build it
this is the issue

**Comment by ErzenT1** [comment]
Go in terminal and add pods in standardCybordExample after that open standardCybordExample
