### ISSUE TITLE
How to get the Facial Landmarks? 

### ISSUE THREAD

**Issue by kushJadia** [StandardCyborg/StandardCyborgCocoa#37]
I have used the below method to show the Preview of the scanned data. 

 **let vc = ScenePreviewViewController(pointCloud: pointCloud, meshTexturing: controller.meshTexturing, landmarks: nil)**

In this method how can I get or Pass the Landmarks?

**Comment by kushJadia** [comment]
Does anyone have any idea about how to get the facial landmarks data using this SDK?

**Comment by aaptho** [comment]
Hello, this SDK does not provide any face landmarking capabilities.

You can use the [Vision framework](https://developer.apple.com/documentation/vision/vndetectfacelandmarksrequest) for calculating 2D face landmarks from an RGB video frame.

`PBFModel` does have support for putting 2D screen-space landmarks onto the 3D model, but it’s not hooked up to anything. If anyone wants to build this support, they are welcome to submit a PR.
