### ISSUE TITLE
Non-manifold edge

### ISSUE THREAD

**Issue by Aniket-Bane** [StandardCyborg/StandardCyborgCocoa#38]
I'm encountering an app crash problem related to the debug message "Non-manifold edge found in mesh topology." I made some changes in the SCMeshingParameters(). Could these changes be the cause of the crash? Please provide assistance.

**Comment by scratchthatitch** [comment]
I have had the same issue. I have posted in another issue thread.

https://github.com/StandardCyborg/StandardCyborgSDK/issues/12#issuecomment-1678665183

**Comment by aaptho** [comment]
This should now be fixed with StandardCyborgFusion 2.3.4! Please reopen this issue if, after updating to the latest via Cocoapods, it still throws this exception.

**Comment by aaptho** [comment]
Apologies, this turned out to be an issue with building the resulting app with Xcode 14.3, not the framework itself. Still an issue.

You can work around this issue for now by building your project with Xcode 14.1.
