### ISSUE TITLE
Is StandardCyborgFusion open source / free for commercial use?

### ISSUE THREAD

**Issue by kashish906** [StandardCyborg/StandardCyborgCocoa#46]
I was a little confused when looking at the StandardCyborgFusion LICENSE [here](https://github.com/StandardCyborg/StandardCyborgCocoa/blob/master/StandardCyborgFusion/LICENSE) since it says that it's proprietary, even though looking at the StandardCyborgSDK [here](https://github.com/StandardCyborg/StandardCyborgSDK/tree/main) is MIT licensed which is open source / free for commercial use. I was wondering if the proprietary license in the StandardCyborgFusion is a mistake, and/or if this allowed for open source / commercial use (since Issue #24 made it seem like it's open source). Thank you for your time!

**Comment by aaptho** [comment]
Good catch on that license file! tl;dr: it is indeed MIT licensed and free for commercial use.

Standard Cyborg was formerly a for-profit startup, and this framework was one product it built and licensed. Now that the startup has closed, they were able to release all the 3D scanning code for free under the MIT license.

It looks like this one license file is not yet updated to match the new terms. I’ll fix that.

**Comment by aaptho** [comment]
Now corrected in StandardCyborgCocoa and StandardCyborgFusion

**Comment by kashish906** [comment]
Thank you for the prompt response and quick fix!
