### ISSUE TITLE
Having trouble running StandardCyborgSDK

### ISSUE THREAD

**Issue by kashish-ops** [StandardCyborg/StandardCyborgCocoa#47]
Hi there, I’ve been having some trouble getting the StandardCyborg app to open up on my iPhone, even though macbook pro and iPhone 13 versions are compatible, I’m not getting any build issues and is successfully building, and Developer Mode is turned on when connecting iPhone to mac. I have tried on another iPhone but facing the same issue. Do you have any recommendations on how to go about this? I’ve looked into many online resources as well, and I’m pretty sure I’ve followed the steps correctly, but would greatly appreciate any insights you may have. Thank you so much!

**Comment by aaptho** [comment]
Hello, can you please share exactly what issue you’re seeing, and after exactly which steps? Does it install to the phone and show up as an app on your Home Screen? And does it launch successfully, or does it crash? If so, please share the crash report

**Comment by kashish906** [comment]
Hi there, after I `cd StandardCyborgExample`, `pod install`, and open up the `.xcworkspace` file, I connected my iPhone 13 to my MacBook Pro and chose the <device> option and selected my iPhone device. It took some time to pair, but after pairing successfully, I clicked on the play button to build the application successfully. I turned on "Developer Mode" on my iPhone, making my phone restart and remain connected to the laptop. I cleaned the build, and built the application again which was a success. However, when I looked at my iPhone, I didn't see the app being installed on the Home Screen. Nope, there was no crash report. All steps seem to be working, except that the app never popped up on my iPhone. (Also I apologize for the different email -- somehow I was on my other account).

**Comment by aaptho** [comment]
Are you able to build and run any other apps, even a new empty app?
And is there anything in the developer console?

**Comment by kashish906** [comment]
I apologize for the late response. I am able to successfully build other apps, but unable to run them. And no, there is no error in the developer console that shows that anything could be wrong.

**Comment by aaptho** [comment]
Sounds like this is an issue with Xcode or iOS, then.
